name: Build and test

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_call:
    inputs:
      hexdoc_release:
        type: boolean
        default: false
  workflow_dispatch:

permissions:
  contents: read

env:
  # adding a branch name here will make hexdoc deploy prerelease versions of your web book on every push to that branch
  # for example: https://hexcasting.hexxy.media/v/latest/main/en_us/
  HEXDOC_BRANCHES: '["main"]'

jobs:
  build-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Build mod
        run: ./gradlew build

      # if this step fails, you need to run your datagen and commit the updated files
      - name: Check if datagen needs to be run
        timeout-minutes: 3
        run: |
          mkdir -p /home/runner/.gradle/caches/fabric-loom/assets
          ./gradlew runAllDatagen
          git add --intent-to-add .
          git diff --name-only --exit-code -- ":!:*/src/generated/resources/.cache/*"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: build/ciArtifacts/
          if-no-files-found: error

  test-mod:
    needs: build-mod
    strategy:
      fail-fast: true
      matrix:
        env:
          - server
          - client
        modloader:
          - fabric
          - forge
        include:
          - modloader: fabric
            mc-runtime-test: fabric
            fabric-api: 0.85.0
            # NOTE: these must be quoted and formatted exactly like this, since they'll be converted into a bash array
            dependencies: >-
              'https://cdn.modrinth.com/data/Ha28R6CL/versions/vlhvI5Li/fabric-language-kotlin-1.10.18%2Bkotlin.1.9.22.jar'
              'https://cdn.modrinth.com/data/lhGA9TYQ/versions/WbL7MStR/architectury-9.2.14-fabric.jar'
              'https://cdn.modrinth.com/data/9s6osm5g/versions/s7VTKfLA/cloth-config-11.1.106-fabric.jar'
              'https://cdn.modrinth.com/data/nTW3yKrm/versions/IvI9LKNc/hexcasting-fabric-1.20.1-0.11.2.jar'
          - modloader: forge
            fabric-api: none
            mc-runtime-test: lexforge
            dependencies: >-
              'https://cdn.modrinth.com/data/lhGA9TYQ/versions/1MKTLiiG/architectury-9.2.14-forge.jar'
              'https://cdn.modrinth.com/data/9s6osm5g/versions/JoLgnJ0G/cloth-config-11.1.106-forge.jar'
              'https://cdn.modrinth.com/data/nTW3yKrm/versions/xENnFQpR/hexcasting-forge-1.20.1-0.11.2.jar'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: mod-build
          path: build/ciArtifacts/
      
      - name: Set up mods folder
        run: |
          mkdir -p run/mods
          cp build/ciArtifacts/*${{ matrix.modloader }}*.jar run/mods

      - name: Download dependencies
        run: |
          for url in "${${{ matrix.dependencies }}}"; do
            wget --directory-prefix=run/mods/ "$url"
          done

      - name: Run MC test client
        if: matrix.env == 'client'
        uses: headlesshq/mc-runtime-test@3.1.1
        with:
          java: 17
          mc: 1.20.1
          modloader: ${{ matrix.modloader }}
          regex: '.*${{ matrix.modloader }}.*'
          fabric-api: ${{ matrix.fabric-api }}
          mc-runtime-test: ${{ matrix.mc-runtime-test }}
      
      - name: Run MC test server
        if: matrix.env == 'server'
        uses: headlesshq/mc-server-test@1.0.0
        with:
          java: 17
          mc: 1.20.1
          modloader: ${{ matrix.modloader }}
          fabric-api: ${{ matrix.fabric-api }}

  build-hexdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    outputs:
      pages-url: ${{ steps.build.outputs.pages-url }}
      deploy: ${{ github.event_name != 'pull_request' && (contains(fromJson(env.HEXDOC_BRANCHES), github.ref_name) || inputs.hexdoc_release) }}
    steps:
      - uses: actions/checkout@v4

      - uses: hexdoc-dev/actions/setup@v1
        with:
          python-version: 3.11

      - id: build
        uses: hexdoc-dev/actions/build@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release: False

  deploy-pages:
    needs:
      - build-hexdoc
    if: needs.build-hexdoc.outputs.deploy == 'true'
    runs-on: ubuntu-latest
    concurrency:
      group: hexdoc-deploy-pages
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: hexdoc-dev/actions/setup@v1
        with:
          python-version: 3.11
        
      - name: Merge new hexdoc build into existing book
        uses: hexdoc-dev/actions/merge@v1
        with:
          release: False
          site-url: ${{ needs.build-hexdoc.outputs.pages-url }}

      # if you want to add extra things to your website (eg. Javadoc/Dokka), add it to _site/dst/docs here

      - name: Deploy to Pages
        uses: hexdoc-dev/actions/deploy-pages@v1
        with:
          merge: false
          release: False
